# This is python3.7/Dockerfile
FROM ubuntu:19.10
MAINTAINER Abram Hindle hindle1@ualberta.ca
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-distutils python3-dev curl wget git vim
# RUN apt-get install -y python3-pip
