# This is python3.7/Dockerfile
FROM ubuntu:18.10
MAINTAINER Abram Hindle hindle1@ualberta.ca
FROM ubuntu:18.10
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3.7 python3.7-dev python3.7-setuptools python3.7-pip curl wget git vim 
